version: '3.0'

services:
  redis:
    image: 'redis:alpine'
    container_name: 'redis-chat-bot'
    networks:
      - chat-bot-network
  telegram-hook:
    depends_on:
      - redis
    image: 'nguyentrminh/os-skkhkt:v0.0.1'
    container_name: 'telegram-hook'
    env_file:
      - server/.env
    networks:
      - chat-bot-network
    ports:
      - "8083:8082"

networks:
  chat-bot-network:
    driver: bridge