version: '3.0'

services:
  robot-support-utils:
    image: 'nguyentrminh/robot-support-utils:v0.0.1'
    container_name: 'robot-support-utils'
    env_file:
      - .env
    networks:
      - chat-bot-network
    devices:
      - "/dev/video0:/dev/video0"
    ports:
      - "8084:8084"

networks:
  chat-bot-network:
    driver: bridge